### ISSUE TITLE
yaml bumper does not handle multi-document yamls

### ISSUE THREAD

**Issue by starpit** [release-it/bumper#24]
Hello there. It looks like the bumper logic here assumes that the parsed documents are objects, not arrays of objects. However, for multi-document yaml files, this is not the case. 

For example:

```yaml
version: 1.0.0
---
version: 1.0.0
```

results this error

> ERROR expected a single document in the stream, but found more
